apiVersion: v1
kind: Service
metadata:
  name: offline-ai-webserver-service
  labels:
    app: offline-ai-webserver
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30081
    protocol: TCP
  selector:
    app: offline-ai-webserver